### ISSUE TITLE
ASCII art output

### ISSUE THREAD

**Issue by undroidwish** [ray2501/tcl-stbimage#2]
Howdy Danilo,

in check-in [1461ef99b9e757c9](https://www.androwish.org/home/info/1461ef99b9e757c9) on www.androwish.org I've added a method to produce ASCII art from the image's bytearray. Just for fun. If you find it useful, I'd be glad if you take it over.

BR,
Christian

**Comment by ray2501** [comment]
Thank you for your effort.

**Comment by ray2501** [comment]
It is done to merge code, so I close this.
